Update reset-nix

diff --git a/nix-out-of-default/bin/reset-nix b/nix-out-of-default/bin/reset-nix
--- a/nix-out-of-default/bin/reset-nix
+++ b/nix-out-of-default/bin/reset-nix
@@ -9,13 +9,18 @@ echo "Restoring nix"
 
 [[ -f /nix/nix/fallback/bin/nix ]] || echo "Nix can't be found" ; exit 2
 
+if [[ ! -f /nix/nix/fallback/bin/nix ]]
+then
+    echo "nix can't be found"
+    exit 2
+fi
 
 /nix/nix/fallback/bin/nix build nixpkgs#nix --out-link /nix/nix/nix
 
 rm -f /etc/systemd/system/nix-daemon.service
 rm -f /etc/systemd/system/nix-daemon.socket
-cp /nix/var/nix/profiles/nix/lib/systemd/system/nix-daemon.service /etc/systemd/system/nix-daemon.service
-cp /nix/var/nix/profiles/nix/lib/systemd/system/nix-daemon.socket /etc/systemd/system/nix-daemon.socket
+cp /nix/nix/nix/lib/systemd/system/nix-daemon.service /etc/systemd/system/nix-daemon.service
+cp /nix/nix/nix/profiles/nix/lib/systemd/system/nix-daemon.socket /etc/systemd/system/nix-daemon.socket
 
 systemctl enable --now nix-daemon.socket
 systemctl enable --now nix-daemon.service
