Update update-nix-fallback

diff --git a/nix-out-of-default/bin/update-nix-fallback b/nix-out-of-default/bin/update-nix-fallback
--- a/nix-out-of-default/bin/update-nix-fallback
+++ b/nix-out-of-default/bin/update-nix-fallback
@@ -5,7 +5,12 @@ if (( $EUID != 0 )); then
     exit 1
 fi
 
-[[ -f /nix/nix/nix/bin/nix ]] || echo "Nix can't be found" ; exit 2
+
+if [[ ! -f /nix/nix/nix/bin/nix ]]
+then
+    echo "nix can't be found"
+    exit 2
+fi
 
 echo "Upgrading nix fallback..."
 
